# Generated by Django 5.1.1 on 2024-09-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermodel',
            name='opinion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='opinion_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='opinion_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='position_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='position_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='position_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
