# Generated by Django 5.1.1 on 2024-09-19 05:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_partnermodel_opinion_en_partnermodel_opinion_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermodel',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='partners/'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='service_images/'),
        ),
    ]
