# Generated by Django 5.1.1 on 2024-09-19 06:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_partnermodel_photo_alter_servicemodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermodel',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
