# Generated by Django 5.1.1 on 2024-09-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_partnermodel_photo_alter_servicemodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicemodel',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
