# Generated by Django 5.1.1 on 2024-09-21 16:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_advicemodel_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', cloudinary.models.CloudinaryField(max_length=255)),
                ('favicon', cloudinary.models.CloudinaryField(max_length=255)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
    ]
